### ISSUE TITLE
README files are not valid Markdown

### ISSUE THREAD

**Issue by wrznr** [syedsaqibbukhari/docanalysis#3]
Although having a corresponding file suffix (i.e `.md`), the different README files in the project are actually not in Markdown format. This results in weird rendering on e.g. GitHub.

**Comment by mmreza79** [comment]
fixed the problem

**Comment by wrznr** [comment]
Great work. Many thanks. However, for `README.md` the issue still persists.
